import type { Metadata } from 'next'
// import './globals.css'
import { ApolloWrapper } from '@/lib/apollo-wrapper'
import * as React from 'react';
import { AppRouterCacheProvider } from '@mui/material-nextjs/v14-appRouter';
import { ThemeProvider } from '@mui/material/styles';
// import Box from '@mui/material/Box';
import theme from '@/theme';
import './globals.css'
import CssBaseline from '@mui/material/CssBaseline';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  return (
    <html lang="en">
      <body style={{ background: theme?.palette?.background?.default }}>
        <ApolloWrapper>
          <AppRouterCacheProvider options={{ enableCssLayer: true }}>
            <ThemeProvider theme={theme}>

              <CssBaseline />
              <body style={{ background: theme?.palette?.background?.default }}>
                {children}
              </body>

            </ThemeProvider>
          </AppRouterCacheProvider>
        </ApolloWrapper>
      </body>
    </html>
  )
}

export default RootLayout 
