import type { Metadata } from 'next'
import './globals.css'
import { ApolloWrapper } from '@/lib/apollo-wrapper'
import * as React from 'react';
import { AppRouterCacheProvider } from '@mui/material-nextjs/v14-appRouter';
import { ThemeProvider } from '@mui/material/styles';
import Box from '@mui/material/Box';
import CssBaseline from '@mui/material/CssBaseline';
import theme from '@/theme';
import Navbar from '@/component/front/Navbar';
import { appWithTranslation } from 'next-i18next'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <AppRouterCacheProvider options={{ enableCssLayer: true }}>
        <ThemeProvider theme={theme}>
          <body style={{ background: theme?.palette?.background?.default }}>
            <ApolloWrapper>
              <CssBaseline />
              {children}
            </ApolloWrapper>
          </body>
        </ThemeProvider>
      </AppRouterCacheProvider>
    </html>
  )
}

export default RootLayout
